// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfxJcbMImQqHrEObReJEIUclRo2irl0qg',
    appId: '1:679089501335:android:eb79752b36227c727325d2',
    messagingSenderId: '679089501335',
    projectId: 'portfolio-3dacb',
    storageBucket: 'portfolio-3dacb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFkxIYxZ0-oueAhLK_iitLPoTa1ruE8C4',
    appId: '1:679089501335:ios:d99a2dc6923da3c27325d2',
    messagingSenderId: '679089501335',
    projectId: 'portfolio-3dacb',
    storageBucket: 'portfolio-3dacb.firebasestorage.app',
    androidClientId: '679089501335-7gibmtnlld4eib45kbtkdqn9hiqm63vb.apps.googleusercontent.com',
    iosClientId: '679089501335-2omnipkg4i47rglj511dshh88oshdj70.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFkxIYxZ0-oueAhLK_iitLPoTa1ruE8C4',
    appId: '1:679089501335:ios:d99a2dc6923da3c27325d2',
    messagingSenderId: '679089501335',
    projectId: 'portfolio-3dacb',
    storageBucket: 'portfolio-3dacb.firebasestorage.app',
    androidClientId: '679089501335-7gibmtnlld4eib45kbtkdqn9hiqm63vb.apps.googleusercontent.com',
    iosClientId: '679089501335-2omnipkg4i47rglj511dshh88oshdj70.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQHnjyIOuPCbYbFgZmlNIRLdxI5-ULF0E',
    appId: '1:679089501335:web:d3e695a8635bc5367325d2',
    messagingSenderId: '679089501335',
    projectId: 'portfolio-3dacb',
    authDomain: 'portfolio-3dacb.firebaseapp.com',
    storageBucket: 'portfolio-3dacb.firebasestorage.app',
    measurementId: 'G-GQC0Z79ET8',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQHnjyIOuPCbYbFgZmlNIRLdxI5-ULF0E',
    appId: '1:679089501335:web:3eaf8ef1c72088287325d2',
    messagingSenderId: '679089501335',
    projectId: 'portfolio-3dacb',
    authDomain: 'portfolio-3dacb.firebaseapp.com',
    storageBucket: 'portfolio-3dacb.firebasestorage.app',
    measurementId: 'G-QCREPK494P',
  );

}