import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

import 'models/templete_card.dart';
import 'theme/style.dart';

void unfocusCurrent() => FocusManager.instance.primaryFocus?.unfocus();

const supportedLocales = [Locale('en'), Locale('ar')];
const translationsPath = 'assets/translations';
List<TempleteModel> getTemplateData() {
  final templates = [
    TempleteModel(
      title: 'Modern Minimalist',
      description: 'Simple clean layout focusing on essential content only',
      icon: Icons.web,
      color: warningYellow.toARGB32(),
      badge: 'Popular',
      features: ['Responsive', 'Fast', 'SEO'],
    ),
    TempleteModel(
      title: 'Creative Portfolio',
      description: 'Bold colorful style perfect for creative professionals',
      icon: Icons.palette,
      color: const Color(0xFF7F1E9D).toARGB32(),
      badge: 'Trending',
      features: ['Animated', 'Gallery', 'Custom'],
    ),
    TempleteModel(
      title: 'Professional',
      description: 'Corporate layout ideal for business and formal content',
      icon: Icons.business_center,
      color: infoColor.toARGB32(),
      badge: 'New',
      features: ['Clean', 'Modern', 'Business'],
    ),
    TempleteModel(
      title: 'Developer Focus',
      description: 'Tech design built for developers to show code and apps',
      icon: Icons.code,
      color: dangerRed.toARGB32(),
      badge: 'Best',
      features: ['Code', 'GitHub', 'Projects'],
    ),
    TempleteModel(
      title: 'Photography',
      description: 'Image-heavy layout ideal for photography portfolios',
      icon: Icons.photo_camera,
      color: 0xFF24884E,
      badge: 'Premium',
      features: ['Gallery', 'Lightbox', 'Portfolio'],
    ),
    TempleteModel(
      title: 'Interactive',
      description: 'Dynamic layout with smooth transitions and motion',
      icon: Icons.touch_app,
      color: 0xFFB7791F,
      badge: 'Hot',
      features: ['3D', 'Animated', 'Modern'],
    ),

    // ------ NEW TEMPLATES ------
    TempleteModel(
      title: 'UI/UX Showcase',
      description: 'Clean template for UI previews and UX case studies',
      icon: Icons.design_services,
      color: 0xFF4A90E2,
      badge: 'UX Ready',
      features: ['Case Studies', 'Prototyping', 'Wireframes'],
    ),
    TempleteModel(
      title: 'Graphic Designer',
      description: 'Visual template for branding, posters, and graphic work',
      icon: Icons.brush,
      color: 0xFFE63946,
      badge: 'Creative',
      features: ['Gallery', 'Branding', 'Print'],
    ),
    TempleteModel(
      title: 'Motion Graphics',
      description: 'Video-first template ideal for motion reels and effects',
      icon: Icons.movie_filter,
      color: 0xFF1D3557,
      badge: 'Studio',
      features: ['Video Reel', 'Transitions', 'Animation'],
    ),
    TempleteModel(
      title: 'Mobile Developer',
      description: 'Modern design to show apps, UI screens, and projects',
      icon: Icons.smartphone,
      color: 0xFF2E8B57,
      badge: 'DevX',
      features: ['Apps', 'Code', 'Screenshots'],
    ),
    TempleteModel(
      title: 'Web Developer',
      description: 'Clean dev layout for sites, demos, and GitHub repos',
      icon: Icons.language,
      color: 0xFF0A9396,
      badge: 'Web Pro',
      features: ['Live Demo', 'Code', 'Responsive'],
    ),
    TempleteModel(
      title: 'Content Creator',
      description: 'Template for creators with blog, video, and social links',
      icon: Icons.mic,
      color: 0xFFF4A261,
      badge: 'Creator',
      features: ['Blog', 'Video', 'Social'],
    ),
    TempleteModel(
      title: '3D Artist',
      description: 'Cinematic style for 3D renders, models, and animations',
      icon: Icons.view_in_ar,
      color: 0xFF6A4C93,
      badge: '3D Pro',
      features: ['Renders', 'Models', 'Showcase'],
    ),
    TempleteModel(
      title: 'Product Designer',
      description: 'Template built for flows, case studies, and product work',
      icon: Icons.devices_other,
      color: 0xFF2A9D8F,
      badge: 'Product',
      features: ['Flows', 'Case Studies', 'UI'],
    ),
    TempleteModel(
      title: 'Marketing Specialist',
      description: 'Portfolio for marketing campaigns and analytics work',
      icon: Icons.analytics,
      color: 0xFFB5179E,
      badge: 'Growth',
      features: ['Campaigns', 'Analytics', 'Brand'],
    ),
    TempleteModel(
      title: 'Freelancer Pro',
      description: 'Universal template for services, pricing, and clients',
      icon: Icons.person,
      color: 0xFF3A86FF,
      badge: 'Global',
      features: ['Services', 'Testimonials', 'Pricing'],
    ),
  ];
  return templates;
}

const supabaseUrl = 'https://zhukfsnlbtcbklkoxwgb.supabase.co';
const supabaseAPIKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpodWtmc25sYnRjYmtsa294d2diIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDgyMTIyNywiZXhwIjoyMDc2Mzk3MjI3fQ.lLKToXtl5KO3jbdsA3kuyRBSrkiotzwTMG9m5sYxTFs';

class FontAwesomeMapper {
  // A curated subset; extend as needed.
  static final Map<String, IconData> _iconMap = {
    'dart': FontAwesomeIcons.dartLang,
    'flutter': FontAwesomeIcons.flutter,
    'github': FontAwesomeIcons.github,
    'google': FontAwesomeIcons.google,
    'instagram': FontAwesomeIcons.instagram,
    'linkedin': FontAwesomeIcons.linkedin,
    'slack': FontAwesomeIcons.slack,
    'address-book': FontAwesomeIcons.addressBook,
    'address-card': FontAwesomeIcons.addressCard,
    'app-store': FontAwesomeIcons.appStore,
    'apple': FontAwesomeIcons.apple,
    'arrow-down': FontAwesomeIcons.arrowDown,
    'arrow-left': FontAwesomeIcons.arrowLeft,
    'arrow-right': FontAwesomeIcons.arrowRight,
    'arrow-up': FontAwesomeIcons.arrowUp,
    'aws': FontAwesomeIcons.aws,
    'angular': FontAwesomeIcons.angular,
    'android': FontAwesomeIcons.android,
    'app-store-ios': FontAwesomeIcons.appStoreIos,
    'at': FontAwesomeIcons.at,
    'atom': FontAwesomeIcons.atom,
    'behance': FontAwesomeIcons.behance,
    'bell': FontAwesomeIcons.bell,
    'bitbucket': FontAwesomeIcons.bitbucket,
    'bitcoin': FontAwesomeIcons.bitcoin,
    'bootstrap': FontAwesomeIcons.bootstrap,
    'bug': FontAwesomeIcons.bug,
    'c': FontAwesomeIcons.c,
    'car': FontAwesomeIcons.car,
    'chart-line': FontAwesomeIcons.chartLine,
    'check': FontAwesomeIcons.check,
    'chrome': FontAwesomeIcons.chrome,
    'cloud': FontAwesomeIcons.cloud,
    'code': FontAwesomeIcons.code,
    'code-branch': FontAwesomeIcons.codeBranch,
    'code-merge': FontAwesomeIcons.codeMerge,
    'code-pull-request': FontAwesomeIcons.codePullRequest,
    'codepen': FontAwesomeIcons.codepen,
    'css3': FontAwesomeIcons.css3,
    'cube': FontAwesomeIcons.cube,
    'database': FontAwesomeIcons.database,
    'dev': FontAwesomeIcons.dev,
    'docker': FontAwesomeIcons.docker,
    'download': FontAwesomeIcons.download,
    'dribbble': FontAwesomeIcons.dribbble,
    'envira': FontAwesomeIcons.envira,
    'envelope': FontAwesomeIcons.envelope,
    'equals': FontAwesomeIcons.equals,
    'ethereum': FontAwesomeIcons.ethereum,
    'exchange': FontAwesomeIcons.rightLeft,
    'expeditedssl': FontAwesomeIcons.expeditedssl,
    'facebook': FontAwesomeIcons.facebook,
    'figma': FontAwesomeIcons.figma,
    'file': FontAwesomeIcons.file,
    'file-code': FontAwesomeIcons.fileCode,
    'file-lines': FontAwesomeIcons.fileLines,
    'file-image': FontAwesomeIcons.fileImage,
    'fire': FontAwesomeIcons.fire,
    'folder': FontAwesomeIcons.folder,
    'git': FontAwesomeIcons.git,
    'gitlab': FontAwesomeIcons.gitlab,
    'globe': FontAwesomeIcons.globe,
    'google-play': FontAwesomeIcons.googlePlay,
    'graduation-cap': FontAwesomeIcons.graduationCap,
    'hashtag': FontAwesomeIcons.hashtag,
    'heart': FontAwesomeIcons.heart,
    'html5': FontAwesomeIcons.html5,
    'image': FontAwesomeIcons.image,
    'java': FontAwesomeIcons.java,
    'javascript': FontAwesomeIcons.js,
    'kaggle': FontAwesomeIcons.kaggle,
    'kitchen-set': FontAwesomeIcons.kitchenSet,
    'laptop': FontAwesomeIcons.laptop,
    'laravel': FontAwesomeIcons.laravel,
    'lightbulb': FontAwesomeIcons.lightbulb,
    'link': FontAwesomeIcons.link,
    'linux': FontAwesomeIcons.linux,
    'lock': FontAwesomeIcons.lock,
    'map': FontAwesomeIcons.map,
    'medium': FontAwesomeIcons.medium,
    'mobile': FontAwesomeIcons.mobile,
    'mongodb': FontAwesomeIcons.envira,
    'moon': FontAwesomeIcons.moon,
    'node': FontAwesomeIcons.node,
    'npm': FontAwesomeIcons.npm,
    'paintbrush': FontAwesomeIcons.paintbrush,
    'paper-plane': FontAwesomeIcons.paperPlane,
    'pen': FontAwesomeIcons.pen,
    'pen-to-square': FontAwesomeIcons.penToSquare,
    'people-group': FontAwesomeIcons.peopleGroup,
    'percent': FontAwesomeIcons.percent,
    'person': FontAwesomeIcons.person,
    'phone': FontAwesomeIcons.phone,
    // 'photoshop': not available directly; use image as placeholder
    'photoshop': FontAwesomeIcons.image,
    'php': FontAwesomeIcons.php,
    'python': FontAwesomeIcons.python,
    'react': FontAwesomeIcons.react,
    'rocket': FontAwesomeIcons.rocket,
    'rss': FontAwesomeIcons.rss,
    'sass': FontAwesomeIcons.sass,
    'search': FontAwesomeIcons.searchengin,
    'server': FontAwesomeIcons.server,
    'share': FontAwesomeIcons.share,
    'wand-magic-sparkles': FontAwesomeIcons.wandMagicSparkles,
    'spinner': FontAwesomeIcons.spinner,
    'star': FontAwesomeIcons.star,
    'stack-overflow': FontAwesomeIcons.stackOverflow,
    'swift': FontAwesomeIcons.swift,
    'tag': FontAwesomeIcons.tag,
    'telegram': FontAwesomeIcons.telegram,
    'thumbs-up': FontAwesomeIcons.thumbsUp,
    'tiktok': FontAwesomeIcons.tiktok,
    'tools': FontAwesomeIcons.screwdriverWrench,
    'trash': FontAwesomeIcons.trash,
    'twitter': FontAwesomeIcons.twitter,
    'ubuntu': FontAwesomeIcons.ubuntu,
    'upload': FontAwesomeIcons.upload,
    'user': FontAwesomeIcons.user,
    'users': FontAwesomeIcons.users,
    'vuejs': FontAwesomeIcons.vuejs,
    'whatsapp': FontAwesomeIcons.whatsapp,
    'windows': FontAwesomeIcons.windows,
    'wordpress': FontAwesomeIcons.wordpress,
    'x-twitter': FontAwesomeIcons.xTwitter,
    'xmark': FontAwesomeIcons.xmark,
    'youtube': FontAwesomeIcons.youtube,
  };

  static List<String> get allIconNames => _iconMap.keys.toList(growable: false);
  static IconData? iconFromName(String name) => _iconMap[name];
}
